version: "3.7"

services:
  xhgui:
    # https://hub.docker.com/r/xhgui/xhgui/tags
    image: xhgui/xhgui:latest
    restart: always
    volumes:
      - ./config:/var/www/xhgui/config
      - ./nginx.conf:/etc/nginx/http.d/default.conf:ro
    environment:
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_DATABASE=xhprof
    ports:
      - "8142:80"

  mongo:
    image: percona/percona-server-mongodb:3.6
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./mongo.init.d:/docker-entrypoint-initdb.d
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  webroot-share:
  mongodb:

# vim:ts=2:sw=2:et
